"""Ports for persistence and external engineering systems."""

from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID

from engineering_gateway.domain.audit import AuditEvent
from engineering_gateway.domain.baselines import Baseline
from engineering_gateway.domain.change_control import ChangeRequest
from engineering_gateway.domain.models import (
    EngineeringElement,
    EngineeringGraph,
    EngineeringRelation,
)
from engineering_gateway.domain.profiles import StandardProfile
from engineering_gateway.domain.workspaces import Workspace


class UnitOfWork(Protocol):
    """Transaction boundary for an atomic Gateway application operation."""

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class ReconciliationCoordinator(Protocol):
    """Exclusive coordination boundary for one workspace reconciliation operation.

    Implementations must serialize reconciliation for the same workspace across the
    scope they advertise. A production coordinator must coordinate across Gateway
    processes, not only within one Python event loop.
    """

    def lock(self, workspace_id: UUID) -> AbstractAsyncContextManager[None]: ...


class EngineeringRepository(Protocol):
    async def get(self, element_id: UUID) -> EngineeringElement | None: ...
    async def save(self, element: EngineeringElement) -> EngineeringElement: ...
    async def add_relation(self, relation: EngineeringRelation) -> EngineeringRelation: ...
    async def get_relations(self, element_id: UUID) -> list[EngineeringRelation]: ...
    async def list_graph(self) -> EngineeringGraph: ...


class WorkspaceChangeSetRepository(Protocol):
    """Isolated overlay for unapproved workspace engineering changes."""

    async def get_element(
        self, workspace_id: UUID, element_id: UUID
    ) -> EngineeringElement | None: ...
    async def save_element(
        self, workspace_id: UUID, element: EngineeringElement
    ) -> EngineeringElement: ...
    async def add_relation(
        self, workspace_id: UUID, relation: EngineeringRelation
    ) -> EngineeringRelation: ...
    async def get_graph(self, workspace_id: UUID) -> EngineeringGraph: ...
    async def get_changes(self, workspace_id: UUID) -> EngineeringGraph: ...


class StandardProfileRegistry(Protocol):
    async def register(self, profile: StandardProfile) -> None: ...
    async def activate(self, profile_id: str, version: str) -> StandardProfile: ...
    async def deactivate(self, profile_id: str, version: str) -> None: ...
    async def is_active(self, profile_id: str, version: str) -> bool: ...
    async def get_active(self) -> list[StandardProfile]: ...
    async def get(self, profile_id: str, version: str) -> StandardProfile | None: ...
    async def list(self) -> list[StandardProfile]: ...


class BaselineRegistryPort(Protocol):
    async def get(self, baseline_id: UUID) -> Baseline | None: ...
    async def register(self, baseline: Baseline) -> Baseline: ...
    async def list(self) -> list[Baseline]: ...


class ChangeRequestRegistryPort(Protocol):
    async def create(self, change_request: ChangeRequest) -> ChangeRequest: ...
    async def get(self, change_request_id: UUID) -> ChangeRequest | None: ...
    async def update(self, change_request: ChangeRequest) -> ChangeRequest: ...


class WorkspaceRegistryPort(Protocol):
    async def get(self, workspace_id: UUID) -> Workspace | None: ...
    async def create(self, workspace: Workspace) -> Workspace: ...
    async def update(self, workspace: Workspace) -> Workspace: ...


class EngineeringSystemAdapter(Protocol):
    system_name: str

    async def get_element(self, external_id: str) -> EngineeringElement | None: ...


class AuditSink(Protocol):
    async def record(self, event: AuditEvent) -> None: ...
